name: ManhuntExtreme
version: 1.3.3.9
main: manhunt_extreme.PluginMain
api-version: 1.18
description: Manhunt plugin with much needed extra features!
commands:
  hunter:
    description: Register a player as a manhunt Hunter.
    usage: /hunter <target>
    permission: manhunt_extreme.hunter
  runner:
    description: Register a player as a manhunt runner.
    usage: /runner <target>
    permission: manhunt_extreme.speedrunner
  spectator:
    description: Register a player as a manhunt Spectator.
    usage: /spectator <target>
    permission: manhunt_extreme.spectator
  clearteams:
    description: Clears teams and removes Discord roles.
    usage: /clearteams
    permission: manhunt_extreme.clearteams
  start:
    description: Start the Manhunt game.
    usage: /start
    permission: manhunt_extreme.start
  end:
    description: Stops the Manhunt game.
    usage: /end
    permission: manhunt_extreme.end
  setheadstart:
    description: Sets the headStartDuration field in plugin config, in seconds.
    usage: /setheadstart <seconds>
    permission: manhunt_extreme.config
  compass:
    description: Use to obtain a compass.
    usage: /compass
    permission: manhunt_extreme.compass
  hunterhelp:
    description: Hunter gets extra advantage when killed by runner.
    usage: /hunterhelp
    permission: manhunt_extreme.hunterhelp
  runnerhelp:
    description: Runner gets extra advantage after killing a hunter.
    usage: /runnerhelp
    permission: manhunt_extreme.runnerhelp
  extradrops:
    description: Drops extra items on hunter deaths.
    usage: /extradrops
    permission: manhunt_extreme.extradrops
  chestgenerate:
    description: Small chance that when a player breaks a block, it turns into a chest with random items.
    usage: /chestgenerate
    permission: manhunt_extreme.chestgenerate
  hasteboost:
    description: Every player has unlimited haste
    usage: /hasteboost
    permission: manhunt_extreme.hasteboost
  allhelp:
    description: Enable all help hunterhelp, runnerhelp, etc.
    usage: /allhelp
    permission: manhunt_extreme.allhelp
  cutclean:
    description: Enables cutclean
    usage: /cutclean
    permission: manhunt_extreme.cutclean
  pause:
    description: Pauses the game
    usage: /pause
    permission: manhunt_extreme.pause
  unpause:
    description: Unpauses the game
    usage: /unpause
    permission: manhunt_extreme.unpause
  health:
    description: Sets the health of the player
    usage: /health <value>
    permission: manhunt_extreme.health
  supplydrops:
    description: Enables supply drops
    usage: /supplydrops
    permission: manhunt_extreme.supplydrops
  jammer:
    description: Toggles the ability to jam compasses
    usage: /jammer
    permission: manhunt_extreme.jammer
